/*
 * jetclocks.h
 */

#ifndef __JETCLOCKS_H__
#define __JETCLOCKS_H__

#define _actmon                     0
#define _adsp                       1
#define _adspneon                   2
#define _ahub                       3
#define _apb2ape                    4
#define _ape                        5
#define _aud_mclk                   6
#define _axi_cbb                    7
#define _can1                       8
#define _can1_host                  9
#define _can2                      10
#define _can2_host
#define _clk_m
#define _dmic1
#define _dmic2
#define _dmic3
#define _dmic4
#define _dpaux
#define _nvjpg1
#define _aclk
#define _mss_encrypt
#define _eqos_rx_input
#define _aon_apb
#define _aon_nic
#define _aon_cpu_nic
#define _plla1
#define _dspk1
#define _dspk2
#define _emc
#define _eqos_axi
#define _eqos_ptp_ref
#define _eqos_rx
#define _eqos_tx
#define _extperiph1
#define _extperiph2
#define _extperiph3
#define _extperiph4
#define _fuse
#define _gpc0clk
#define _gpu_pwr
#define _host1x
#define _xusb_hs_hsicp
#define _i2c1
#define _i2c2
#define _i2c3
#define _i2c4
#define _i2c6
#define _i2c7
#define _i2c8
#define _i2c9
#define _i2s1
#define _i2s1_sync_input
#define _i2s2
#define _i2s2_sync_input
#define _i2s3
#define _i2s3_sync_input
#define _i2s4
#define _i2s4_sync_input
#define _i2s5
#define _i2s5_sync_input
#define _i2s6
#define _i2s6_sync_input
#define _isp
#define _eqos_rx_m
#define _maud
#define _mipi_cal
#define _mphy_core_pll_fixed
#define _mphy_l0_rx_ana
#define _mphy_l0_rx_ls_bit
#define _mphy_l0_rx_symb
#define _mphy_l0_tx_ls_3xbit
#define _mphy_l0_tx_symb
#define _mphy_l1_rx_ana
#define _mphy_tx_1mhz_ref
#define _nvcsi
#define _nvcsilp
#define _nvdec
#define _hub
#define _disp
#define _nvdisplay_p0
#define _nvdisplay_p1
#define _dsc
#define _nvenc
#define _nvjpg
#define _osc
#define _aon_touch
#define _plla
#define _pllaon
#define _plle
#define _pllp
#define _pllp_out0
#define _utmip_pll
#define _plla_out0
#define _pwm1
#define _pwm2
#define _pwm3
#define _pwm4
#define _pwm5
#define _pwm6
#define _pwm7
#define _pwm8
#define _rce_cpu_nic
#define _rce_nic
#define _aon_i2c_slow
#define _sce_cpu_nic
#define _sce_nic
#define _sdmmc1
#define _uphy_pll3
#define _sdmmc4
#define _se
#define _sor0_pll_ref
#define _sor0_ref
#define _sor1_pll_ref
#define _pre_sor0_ref
#define _sor1_ref
#define _pre_sor1_ref
#define _sor_safe
#define _dmic5
#define _spi1
#define _spi2
#define _spi3
#define _i2c_slow
#define _sync_dmic1
#define _sync_dmic2
#define _sync_dmic3
#define _sync_dmic4
#define _sync_dspk1
#define _sync_dspk2
#define _sync_i2s1
#define _sync_i2s2
#define _sync_i2s3
#define _sync_i2s4
#define _sync_i2s5
#define _sync_i2s6
#define _mphy_force_ls_mode
#define _tach0
#define _tsec
#define _tsec_pka
#define _uarta
#define _uartb
#define _uartc
#define _uartd
#define _uarte
#define _uartf
#define _pex1_c6_core
#define _uart_fst_mipi_cal
#define _ufsdev_ref
#define _ufshc
#define _usb2_trk
#define _vi
#define _vic
#define _csite
#define _ist
#define _jtag_intfc_pre_cg
#define _pex2_c7_core
#define _pex2_c8_core
#define _pex2_c9_core
#define _dla0_falcon
#define _dla0_core
#define _dla1_falcon
#define _dla1_core
#define _sor0
#define _sor1
#define _sor_pad_input
#define _pre_sf0
#define _sf0
#define _sf1
#define _dsi_pad_input
#define _pex2_c10_core
#define _uarti
#define _uartj
#define _uarth
#define _fuse_serial
#define _qspi0_2x_pm
#define _qspi1_2x_pm
#define _qspi0_pm
#define _qspi1_pm
#define _vi_const
#define _nafll_bpmp
#define _nafll_sce
#define _nafll_nvdec
#define _nafll_nvjpg
#define _nafll_tsec
#define _nafll_vi
#define _nafll_se
#define _nafll_nvenc
#define _nafll_isp
#define _nafll_vic
#define _nafll_axicbb
#define _nafll_nvjpg1
#define _nafll_pva0_core
#define _nafll_pva0_vps
#define _dbgapb
#define _nafll_rce
#define _la
#define _pllp_out_jtag
#define _sdmmc4_axicif
#define _sdmmc_legacy_tm
#define _pex0_c0_core
#define _pex0_c1_core
#define _pex0_c2_core
#define _pex0_c3_core
#define _pex0_c4_core
#define _pex1_c5_core
#define _pex0_c0_core_m
#define _pex0_c1_core_m
#define _pex0_c2_core_m
#define _pex0_c3_core_m
#define _pex0_c4_core_m
#define _pex1_c5_core_m
#define _pex1_c6_core_m
#define _gpc1clk
#define _pllc4
#define _pllc4_out1
#define _pllc4_out2
#define _pllc4_muxed
#define _pllc4_vco_div2
#define _pllnvhs
#define _pex2_c7_core_m
#define _pex2_c8_core_m
#define _pex2_c9_core_m
#define _pex2_c10_core_m
#define _mgbe0_rx_input
#define _mgbe1_rx_input
#define _mgbe2_rx_input
#define _mgbe3_rx_input
#define _pex_sata_usb_rx_byp
#define _pex_usb_pad_pll0_mgmt
#define _pex_usb_pad_pll1_mgmt
#define _pex_usb_pad_pll2_mgmt
#define _pex_usb_pad_pll3_mgmt
#define _nvhs_rx_byp_ref
#define _nvhs_pll0_mgmt
#define _xusb_core_dev
#define _xusb_core_mux
#define _xusb_core_host
#define _xusb_core_ss
#define _xusb_falcon
#define _xusb_falcon_host
#define _xusb_falcon_ss
#define _xusb_fs
#define _xusb_fs_host
#define _xusb_fs_dev
#define _xusb_ss
#define _xusb_ss_dev
#define _xusb_ss_superspeed
#define _nafll_cluster0
#define _nafll_cluster1
#define _nafll_cluster2
#define _can1_core
#define _can2_core
#define _plla1_out1
#define _pllnvhs_hps
#define _pllrefe_vcoout
#define _clk_32k
#define _utmipll_clkout48
#define _utmipll_clkout480
#define _pllnvcsi
#define _pva0_cpu_axi
#define _pva0_vps
#define _nafll_dla0_core
#define _nafll_dla0_falcon
#define _nafll_dla1_core
#define _nafll_dla1_falcon
#define _aon_uart_fst_mipi_cal
#define _gpusys
#define _i2c5
#define _fr_se
#define _bpmp_cpu_nic
#define _bpmp_cpu
#define _tsc
#define _emcsa_mpll
#define _emcsb_mpll
#define _emcsc_mpll
#define _emcsd_mpll
#define _pllc
#define _pllc2
#define _tsc_ref
#define _fuse_burn
#define _pllgbe
#define _pllgbe_hps
#define _emcsa_emc
#define _emcsb_emc
#define _emcsc_emc
#define _emcsd_emc
#define _plle_hps
#define _pllrefe_vcoout_gated
#define _pllp_div17
#define _soc_therm
#define _tsense
#define _fr_seu1
#define _nafll_ofa
#define _ofa
#define _nafll_seu1
#define _seu1
#define _spi4
#define _spi5
#define _dce_cpu_nic
#define _dce_nic
#define _nafll_dce
#define _mphy_l0_rx_ana_m
#define _mphy_l1_rx_ana_m
#define _mphy_l0_tx_pre_symb
#define _mphy_l0_tx_ls_symb_div
#define _mphy_l0_tx_2x_symb
#define _mphy_l0_tx_hs_symb_div
#define _mphy_l0_tx_ls_3xbit_div
#define _mphy_l0_tx_mux_symb_div
#define _mphy_l0_tx_symb_m
#define _mphy_l0_rx_ls_symb_div
#define _mphy_l0_rx_hs_symb_div
#define _mphy_l0_rx_ls_bit_div
#define _mphy_l0_rx_mux_symb_div
#define _mphy_l0_rx_symb_m
#define _mgbe0_rx_input_m
#define _mgbe1_rx_input_m
#define _mgbe2_rx_input_m
#define _mgbe3_rx_input_m
#define _mgbe0_rx_pcs_m
#define _mgbe1_rx_pcs_m
#define _mgbe2_rx_pcs_m
#define _mgbe3_rx_pcs_m
#define _tach1
#define _mgbes_app
#define _uphy_gbe_pll2_tx_ref
#define _uphy_gbe_pll2_xdig
#define _mgbe0_rx_pcs_input
#define _mgbe1_rx_pcs_input
#define _mgbe2_rx_pcs_input
#define _mgbe3_rx_pcs_input
#define _mgbe0_rx_pcs
#define _mgbe0_tx
#define _mgbe0_tx_pcs
#define _mgbe0_mac_divider
#define _mgbe0_mac
#define _mgbe0_macsec
#define _mgbe0_eee_pcs
#define _mgbe0_app
#define _mgbe0_ptp_ref
#define _mgbe1_rx_pcs
#define _mgbe1_tx
#define _mgbe1_tx_pcs
#define _mgbe1_mac_divider
#define _mgbe1_mac
#define _mgbe1_macsec
#define _mgbe1_eee_pcs
#define _mgbe1_app
#define _mgbe1_ptp_ref
#define _mgbe2_rx_pcs
#define _mgbe2_tx
#define _mgbe2_tx_pcs
#define _mgbe2_mac_divider
#define _mgbe2_mac
#define _mgbe2_macsec
#define _mgbe2_eee_pcs
#define _mgbe2_app
#define _mgbe2_ptp_ref
#define _mgbe3_rx_pcs
#define _mgbe3_tx
#define _mgbe3_tx_pcs
#define _mgbe3_mac_divider
#define _mgbe3_mac
#define _mgbe3_macsec
#define _mgbe3_eee_pcs
#define _mgbe3_app
#define _mgbe3_ptp_ref
#define _gbe_rx_byp_ref
#define _gbe_pll0_mgmt
#define _gbe_pll1_mgmt
#define _gbe_pll2_mgmt
#define _eqos_macsec_rx
#define _eqos_macsec_tx
#define _eqos_tx_divider
#define _nvhs_pll1_mgmt
#define _emchub
#define _i2s7_sync_input
#define _sync_i2s7
#define _i2s7
#define _i2s7_pad_m
#define _i2s8_sync_input
#define _sync_i2s8
#define _i2s8
#define _i2s8_pad_m
#define _nafll_gpc0
#define _nafll_gpc1
#define _nafll_gpusys
#define _nafll_dsu0
#define _nafll_dsu1
#define _nafll_dsu2
#define _sce_cpu
#define _rce_cpu
#define _dce_cpu
#define _dsipll_vco
#define _dsipll_clkoutpn
#define _dsipll_clkouta
#define _sppll0_vco
#define _sppll0_clkoutpn
#define _sppll0_clkouta
#define _sppll0_clkoutb
#define _sppll0_div10
#define _sppll0_div25
#define _sppll0_div27pn
#define _sppll1_vco
#define _sppll1_clkoutpn
#define _sppll1_div27pn
#define _vpll0_ref
#define _vpll0
#define _vpll1
#define _nvdisplay_p0_ref
#define _rg0
#define _rg1
#define _disppll
#define _disphubpll
#define _dsi_lp
#define _aza_2xbit
#define _aza_bit
#define _dsi_core
#define _dsi_pixel
#define _pre_sor0
#define _pre_sor1
#define _dp_link_ref
#define _sor_linka_input
#define _sor_linka_afifo
#define _sor_linka_afifo_m
#define _rg0_m
#define _rg1_m
#define _sor0_m
#define _sor1_m
#define _pllhub
#define _mchub
#define _emcsa_mc
#define _emcsb_mc
#define _emcsc_mc
#define _emcsd_mc
